version: '3'

volumes:
  uptime_monitor_local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: uptime_monitor_local_django
    container_name: uptime_monitor_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - .envs/.django
      - .envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14
    container_name: uptime_monitor_local_postgres
    volumes:
      - uptime_monitor_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres



  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: uptime_monitor_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: uptime_monitor_local_redis

  celeryworker:
    <<: *django
    image: uptime_monitor_local_celeryworker
    container_name: uptime_monitor_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celeryworker-save-history:
    <<: *django
    image: uptime_monitor_local_celeryworker
    container_name: uptime_monitor_local_celeryworker-save-history
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []

    command: watchfiles celery.__main__.main --args '-A config.celery_app worker -Q response_history -l INFO'
  celerybeat:
    <<: *django
    image: uptime_monitor_local_celerybeat
    container_name: uptime_monitor_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: uptime_monitor_local_flower
    container_name: uptime_monitor_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
