# Generated by Django 4.0.8 on 2023-05-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='siteresponsehistory',
            index=models.Index(fields=['check_registry'], name='core_sitere_check_r_b2c22d_idx'),
        ),
    ]
